const arr = [
  'Abstraction',
  'Accessibility',
  'Adobe Flash',
  'AJAX',
  'Algorithm',
  'API',
  'Apple Safari',
  'Application Context',
  'Argument',
  'ARIA',
  'ARPA',
  'Arpanet',
  'Array',
  'ASCII',
  'Asynchronous',
  'ATAG',
  'Attribute',
  'Bandwidth',
  'BiDi',
  'Blink',
  'Block',
  'Block',
  'Boolean',
  'Boot2Gecko',
  'Bounding Box',
  'Browser',
  'Browsing context',
  'buffer',
  'Cacheable',
  'CalDAV',
  'Call stack',
  'Callback function',
  'Canonical order',
  'Canvas',
  'Card sorting',
  'CardDAV',
  'caret',
  'CDN',
  'Certificate authority',
  'Certified',
  'Challenge-response authentication',
  'Character',
  'Character encoding',
  'Chrome',
  'CIA',
  'Cipher',
  'Cipher suite',
  'Ciphertext',
  'Class',
  'Closure',
  'CMS',
  'Codec',
  'Compile',
  'Compile time',
  'Computer Programming',
  'Conditional',
  'Constant',
  'Constructor',
  'Control flow',
  'Cookie',
  'Copyleft',
  'CORS',
  'Crawler',
  'CRLF',
  'Cross-site scripting',
  'CRUD',
  'Cryptanalysis',
  'Cryptographic hash function',
  'Cryptography',
  'CSP',
  'CSRF',
  'CSS',
  'CSS preprocessor',
  'Data structure',
  'Decryption',
  'Denial of Service',
  'Descriptor',
  'Deserialization',
  'Developer Tools',
  'DHTML',
  'Digest',
  'Digital certificate',
  'Distributed Denial of Service',
  'DMZ',
  'DNS',
  'Doctype',
  'Document directive',
  'document environment',
  'DOM',
  'Domain',
  'Domain name',
  'Dominator',
  'DoS attack',
  'DTD',
  'DTMF',
  'Dynamic programming language',
  'Dynamic typing',
  'ECMA',
  'ECMAScript',
  'Element',
  'Empty element',
  'Encapsulation',
  'Encryption',
  'Endianness',
  'Engine',
  'Entity',
  'Entity header',
  'Event',
  'Exception',
  'Expando',
  'Falsy',
  'Fetch directive',
  'Firefox OS',
  'firewall',
  'First-class Function',
  'Forbidden header name',
  'Forbidden response header name',
  'FTP',
  'FTU',
  'Function',
  'Gaia',
  'Garbage collection',
  'Gecko',
  'General header',
  'GIF',
  'GIJ',
  'Git',
  'Global attribute',
  'Global object',
  'Global scope',
  'Global variable',
  'Gonk',
  'Google Chrome',
  'GPL',
  'GPU',
  'Graceful degradation',
  'Grid',
  'Grid Areas',
  'Grid Axis',
  'Grid Cell',
  'Grid Column',
  'Grid Lines',
  'Grid Row',
  'Grid Tracks',
  'Guard',
  'Gutters',
  'GZip compression',
  'Hash',
  'Head',
  'Header',
  'High-level programming language',
  'HMAC',
  'Hoisting',
  'Host',
  'Hotlink',
  'HPKP',
  'HSTS',
  'HTML',
  'HTML5',
  'HTTP',
  'HTTPS',
  'Hyperlink',
  'Hypertext',
  'I18N',
  'IANA',
  'ICANN',
  'ICE',
  'IDE',
  'Idempotent',
  'Identifier',
  'IDL',
  'IETF',
  'IIFE',
  'IMAP',
  'Immutable',
  'Index',
  'IndexedDB',
  'Information architecture',
  'Inheritance',
  'Instance',
  'Internet',
  'IP Address',
  'IPv4',
  'IPv6',
  'IRC',
  'ISO',
  'ISP',
  'Jank',
  'Java',
  'JavaScript',
  'JPEG',
  'jQuery',
  'JSON',
  'Key',
  'Keyword',
  'LGPL',
  'Ligature',
  'Local scope',
  'Local variable',
  'Locale',
  'Localization',
  'loop',
  'ltr',
  'MathML',
  'Metadata',
  'Method',
  'Microsoft Edge',
  'Microsoft Internet Explorer',
  'Middleware',
  'mime',
  'MIME type',
  'MitM',
  'Mixin',
  'Mobile First',
  'Modem',
  'Modern web apps',
  'Modularity',
  'Mozilla Firefox',
  'Mutable',
  'MVC',
  'Namespace',
  'NaN',
  'NAT',
  'Native',
  'Navigation directive',
  'Netscape Navigator',
  'NNTP',
  'Node',
  'Node',
  'Node',
  'Node.js',
  'non-normative',
  'Normative',
  'Null',
  'Number',
  'Object',
  'Object reference',
  'OOP',
  'OpenGL',
  'OpenSSL',
  'Opera Browser',
  'Operand',
  'Operator',
  'Origin',
  'OTA',
  'OWASP',
  'P2P',
  'PAC',
  'Parameter',
  'Parent object',
  'Parse',
  'Parser',
  'PDF',
  'Percent-encoding',
  'PHP',
  'Pixel',
  'Placeholder names',
  'Plaintext',
  'PNG',
  'Polyfill',
  'Polymorphism',
  'POP3',
  'Port',
  'Preflight request',
  'Presto',
  'Primitive',
  'Privileged',
  'privileged code',
  'Progressive Enhancement',
  'Progressive web apps',
  'Property',
  'Protocol',
  'Prototype',
  'Prototype-based programming',
  'Proxy server',
  'Pseudo-class',
  'Pseudo-element',
  'Pseudocode',
  'Python',
  'Quality values',
  'Random Number Generator',
  'Raptor',
  'Raster image',
  'RDF',
  'Recursion',
  'Reference',
  'Reflow',
  'Regular expression',
  'Rendering engine',
  'Repo',
  'Reporting directive',
  'Request header',
  'Response header',
  'Responsive web design',
  'REST',
  'RGB',
  'RIL',
  'Robots.txt',
  'RSS',
  'RTF',
  'rtl',
  'Ruby',
  'Safe',
  'SCM',
  'Scope',
  'Script-supporting element',
  'SCTP',
  'SDP',
  'Search engine',
  'Second-level Domain',
  'Selector',
  'Semantics',
  'SEO',
  'Serialization',
  'Server',
  'Session Hijacking',
  'SGML',
  'Shim',
  'Signature',
  'SIMD',
  'Simple header',
  'Simple response header',
  'SISD',
  'SLD',
  'Sloppy mode',
  'Slug',
  'Smoke Test',
  'SMTP',
  'SOAP',
  'Specification',
  'SQL',
  'SQL Injection',
  'SRI',
  'SSL',
  'Stacking context',
  'State machine',
  'Statement',
  'Static typing',
  'String',
  'STUN',
  'SVG',
  'SVN',
  'Symbol',
  'Synchronous',
  'Syntax',
  'Syntax error',
  'Tag',
  'TCP',
  'Telnet',
  'Three js',
  'TLD',
  'TLS',
  'TOFU',
  'Tree shaking',
  'Trident',
  'Truthy',
  'TTL',
  'TURN',
  'Type',
  'Type Conversion',
  'UDP',
  'UI',
  'undefined',
  'Unicode',
  'URI',
  'URL',
  'URN',
  'Usenet',
  'User agent',
  'UTF-8',
  'UX',
  'Validator',
  'Value',
  'Variable',
  'Vendor Prefix',
  'Viewport',
  'VoIP',
  'W3C',
  'WAI',
  'WCAG',
  'Web standards',
  'WebDAV',
  'WebExtensions',
  'WebGL',
  'WebIDL',
  'WebKit',
  'WebM',
  'WebP',
  'WebRTC',
  'WebSockets',
  'WebVTT',
  'WHATWG',
  'World Wide Web',
  'Wrapper',
  'XForm',
  'XHR',
  'XMLHttpRequest',
  'XHTML',
  'XInclude',
  'XLink',
  'XML',
  'XPath',
  'XQuery',
  'XSLT',
  'Other',
  '404',
  '502',
]

module.exports = arr.reduce((dict, term) => {
  dict[term.toLowerCase()] = true;
  return dict;
}, {});
